apiVersion: v1
kind: Secret
metadata:
  name: example-creds
  namespace: default
type: Opaque
stringData:
  credentials: |
    {
      "secret_id": "AKIDmOsAF9qKcmkVyEGBzb0DIApGcvR8oLmH",
      "secret_key": "ZDoYEzpqklmt8HXgdMsPABAB6wjOp35u",
      "region": "ap-hongkong"
    }